flow.cabal, src/Network/AWS/Flow.hs, src/Network/AWS/Flow/Helper.hs, src/Network/AWS/Flow/Internal.hs, src/Network/AWS/Flow/S3.hs, src/Network/AWS/Flow/SWF.hs, src/Network/AWS/Flow/Types.hs, src/Network/AWS/SWF/Flow/Internal.hs, src/main/Act.hs, src/main/Decide.hs, src/main/Execute.hs, src/main/Register.hs
Publish artifacts in S3.
Move domain in to config.
Other cleanup.
=> Artifact publishing in S3

examples/build.sh, examples/cfg/config.yaml, examples/cfg/hello.yaml, examples/cfg/world.yaml, examples/docker-compose.yml, examples/execute.json, examples/hello-world/Dockerfile, examples/hello-world/hello.py, examples/hello-world/world.py, examples/run.sh
Simple Hello world example.
/cc @kovach @denniszollo
=> Hello World Example

examples/hello-world/run-containerless.sh, main/Act.hs
Switch the logic around.
/cc @scottswift
=> Switch Logic

examples/hello-world/hello-world/hello.py, examples/hello-world/hello-world/world.py, examples/hello-world/run-containerless.sh, main/Act.hs, main/Options.hs, src/Network/AWS/Flow.hs, src/Network/AWS/Flow/S3.hs, src/Network/AWS/Flow/Types.hs, stack.yaml
Load artifacts for the workers.
/cc @scottswift @benjamin0
=> Preload artifacts

examples/hello-world/hello-world/world.py
Change world.py output artifacts directory to reflect updated convention.
@mfine
=> Change world.py output artifacts directory

examples/hello-world/run-containerless.sh, examples/hello-world/run.sh, src/Network/AWS/Flow.hs
Eat these errors.
/cc @benjamin0
=> Suppress registering stuff that's already registered

src/Network/AWS/Flow.hs, src/Network/AWS/Flow/Prelude.hs
Ability to log out the inputs and outputs.
/cc @benjamin0
=> Debug inputs and outputs

src/Network/AWS/Flow.hs
Keep wrapping serialize errors. See https://github.com/brendanhay/amazonka/issues/285.
=> Wrap serialize errors

examples/hello-world/run-containerless2.sh, main/Act2.hs, main/Options.hs, wolf.cabal
Lose the container. Compression by default. Eventually remove `act`.
/cc @swift-nav/hitl
=> act2 - container free act with default compression

src/Network/AWS/Flow.hs, src/Network/AWS/Flow/Env.hs, src/Network/AWS/Flow/Prelude.hs, src/Network/AWS/Flow/SWF.hs, wolf.cabal
If the process returns a non 0 exit code, look for a -1 exit code (255) and cancel the workflow.
/cc @margaret
=> Cancel workflows

main/Act2.hs, main/Options.hs
Add a gzipless flag - grabs some behavior from Act.hs, with inverted logic.
/cc @JoshuaGross
=> Add a gzipless flag

src/Network/AWS/Wolf/Act.hs, src/Network/AWS/Wolf/Ctx.hs, src/Network/AWS/Wolf/Decide.hs, src/Network/AWS/Wolf/Types/Ctx.hs, stack.yaml
Instrument wolf for metrics. Counts around polling and actions/decisions, elapsed times around polling and actions. Also surface exceptions and throttling.
/cc @cbeighley @margaret
=> Wolf Metrics

main/actor.hs, src/Network/AWS/Wolf/Act.hs
A quiesce file will stop a running actor.
/cc @axlan
=> Quiesce to stop a running actor

src/Network/AWS/Wolf/Act.hs, src/Network/AWS/Wolf/File.hs, src/Network/AWS/Wolf/Prelude.hs, src/Network/AWS/Wolf/S3.hs, src/Network/AWS/Wolf/SWF.hs, wolf.cabal, wolf.cabal.m4
=> Direct to S3

main/actor.hs, main/counter.hs, main/decider.hs, src/Network/AWS/Wolf/Act.hs, src/Network/AWS/Wolf/Count.hs, src/Network/AWS/Wolf/Decide.hs, src/Network/AWS/Wolf/Prelude.hs
Allow the buckets and domains to be overwritten
/cc @axlan
=> Override domain and bucket, optionally

main/actor.hs, src/Network/AWS/Wolf/Act.hs, src/Network/AWS/Wolf/Prelude.hs
=> Add an include filter

.travis.yml, README.md, stack.yaml
=> Fix installation

main/actor.hs, src/Network/AWS/Wolf/Act.hs
Be able to run multiple queues - cycle through them.
=> Support running multiple queues

main/actor.hs, src/Network/AWS/Wolf/Act.hs
Make the interval flag optional, and have that drive heartbeating.
=> Also optionally heartbeating

src/Network/AWS/Wolf/Act.hs
I was running into a problem in SITL's integration test suite where the second step in a workflow was trying to download the previous step's output before it got uploaded. I think we need to call `upload osd` before calling `completeActivity`
=> Upload output immediately after running the command

.gitignore, main/actor.hs, src/Network/AWS/Wolf/Act.hs
Disable uploads/downloads to/from S3.
=> Flag to disable s3
